apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: webserver
  name: webserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webserver
    spec:
      containers:
      - image: kuberaj/project_001:156
        name: webserver
        resources: {}
         ports: 
        - containerPort: 80
        - containerPort: 443
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lbservice
spec:
  selector:
    app: webserver
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
