apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: webserver
  name: webserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webserver
    spec:
      containers:
      - image: kuberaj/project_001:147
        name: webserver
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: NodePort
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 32000
  selector:
    app: webserver
