apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: webserver
  name: webserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webserver
    spec:
      containers:
      - image: kuberaj/project_001:161
        name: webserver
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: webserver
---
apiVersion: v1
kind: Service
metadata:
  name: np-service
  labels:
    run: webserver
spec:
  type: NodePort
  ports:
  - port: 8082
    protocol: TCP
  selector:
    run: webserver
