apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: webserver
  name: webserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webserver
    spec:
      containers:
      - image: kuberaj/project_001:148
        name: webserver
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  externalIPs:
  - 192.168.0.10
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: webserver
    
---

apiVersion: v1
kind: Service
metadata:
 name: nodesvc
spec:
 type: NodePort
 selector:
   app: webserver
   env: prod
 ports:
 - nodePort: 32410
   protocol: TCP
   port: 8082
   targetPort: 82
